// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SddDemo.Ledger.Infrastructure.Migrations;

#nullable disable

namespace SddDemo.Ledger.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(LedgerMigrationsDbContext))]
    partial class LedgerMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SddDemo.Ledger.Infrastructure.Migrations.LedgerAuditRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("EventAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("event_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("EventAt")
                        .HasDatabaseName("ix_ledger_audit_event_at");

                    b.HasIndex("LedgerId", "EventAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ledger_audit_ledger_event_at");

                    b.ToTable("ledger_audit", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_type", "event_type IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("SddDemo.Ledger.Infrastructure.Migrations.LedgerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Status", "LastModifiedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_ledger_owner_status_lastmodified");

                    b.ToTable("ledger", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_currency_alpha3", "currency_code ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_ledger_status", "status IN (1, 2)");

                            t.HasCheckConstraint("ck_ledger_version_positive", "version >= 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
